### ISSUE TITLE
Token size limitation

### ISSUE THREAD

**Issue by pedrompcaetano** [Casvt/Noted#86] opened 2024-05-26 19:19 UTC
**Description of the bug**
Using a automatically generated token from apprise does not work. (65 characters)

**To Reproduce**
1. On Apprise webAPI, generate click 'New configuration' and copy the 'Management for Config ID'
2. Setup a new Notification Service => Apprise
3. Input hostname and token
4. Unable to click test, token is deemed invalid

**Expected behaviour**
It should be possible to use the generated token.
Testing via 3rd party (curl) works as expected.

**Version info**
Client
 - OS: Fedora Kinoite 40
 - Browser: Firefox
Server
 - docker MIND Version: v1.4.0

**Comment by Casvt** [comment] 2024-07-14 13:11
The maximum length of the token allowed by apprise (to be specific: the regex for the field supplied by apprise) is 128 characters. So where does the "65" characters come from? What do the logs say?

**Comment by ovargasp** [comment] 2024-07-17 18:22
Hi,

I'm seen the same thing I think, there is nothing in the logs because it doesn't get to be saved. I noticed that the field became red when I tried to save the 65 characters key, so I decided to cut the key short to test, and it saved the value and then it gave the invalid key error in the logs.

This is what i got from my tests:
this leght is UI valid: 12345678901234567890123456789012
![image](https://github.com/user-attachments/assets/783039f6-42a7-44a8-959f-ede7d9380c49)
as you can see is not red, and allows you to run the test and save.

If you add one more character it will show the red interface warning and it won't save it... so this is what a non go looks like: lenght: 123456789012345678901234567890123
![image](https://github.com/user-attachments/assets/47c2b821-c399-4781-8343-e57a070de3ff)

And the same happens if you try to edit and change the short key for the correct one, it goes red and it doesn't save... (I tried that to see it it worked)

I hope this helps to clarify or at least add some more information to this post.

**Comment by ovargasp** [comment] 2024-07-17 21:34
So I did a little "googling" on this and found that there is a change in Apprise API version 1.8.0 (the autogenerated token lenght) it seems now it's 64 bits and before it used to be 32 bits. The  Mind docker image has Apprise CLI version v1.7.4, and that version as the previous ones uses the 32 bits token, so when I tried to use the 64 bit token it errored saying: **ERROR - Could not load Apprise API URL: apprise://X...X:8000/7...3/** even though I could test it successfully on the API UI as @pedrompcaetano said. 

So it's kind of a backwards compatibility issue in the Apprise API, to work arround it you can manually generate a 32 bits key in Apprise API and it will work with both Mind docker and Apprise API docker latest. Once you do that it works flowlessly

Here you have a post that explains it all:

https://github.com/louislam/uptime-kuma/issues/4928

By the way @Casvt I find your software really cool and it saved me a lot of work and troubles... thanx

**Comment by Casvt** [comment] 2024-07-18 13:51
Okay so I basically need to update the apprise dependency. Even though the cause is different, the result is the same as #85. So I'll be closing this issue as the same actions are required as for that issue.

**Closed as not planned by Casvt** 2024-07-18 13:51 UTC
Labels: bug
