### ISSUE TITLE
Can it support Chinese lunar calendar event reminders

### ISSUE THREAD

**Issue by gygy** [Casvt/Noted#82] opened 2024-04-15 22:02 UTC
This is a very impressive program. Can it support Chinese lunar calendar event reminders?

**Comment by Casvt** [comment] 2024-04-16 10:29
Not a duplicate of #79, but this has the same reason as that one for why I'm going to decline. It's explained here: https://github.com/Casvt/MIND/issues/79#issuecomment-2017759379

**Closed as not planned by Casvt** 2024-04-16 10:29 UTC
Labels: enhancement
